# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Home"
  url = "#about"
  weight = 10

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 20

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

[[main]]
  name = "Deliverables"
  url = "Deliverables/"
  weight = 40

  [[main]]
    name = "Course Content"
    identifier = "course-parent"
    url = ""
    weight = 41

  [[main]]
    name = "Session 1"
    parent = "course-parent"
    url = "course/session-1/"
    weight = 50

    [[main]]
      name = "Session 2"
      parent = "course-parent"
      url = "course/session-2/"
      weight = 60

      [[main]]
        name = "Session 3"
        parent = "course-parent"
        url = "course/session-3/"
        weight = 70

        [[main]]
          name = "Session 4"
          parent = "course-parent"
          url = "course/session-4/"
          weight = 80


    [[main]]
       name = "Course Outline"
    url = "https://www.dropbox.com/sh/3ctg8zp4cgwpae5/AADddVHYn3dzqEbZ_nt_sclTa?dl=0&preview=MFIT842_CourseOutline.docx"
       weight = 200

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/cv.pdf"
#    weight = 70
